Repository godotengine/godot-asset-library, pull requests merged in 2020-04, with the labels that each got.

#209 Remove download hashes
  API.md
  data/data.sql
  data/migration-7.sql
  src/Helpers/Utils.php
  src/queries.php
  src/routes/asset.php
  src/routes/asset_edit.php
  templates/_asset_fields.phtml
  templates/asset.phtml
  templates/asset_edit.phtml
Labels: enhancement, topic:backend, topic:frontend

#212 README: Link to API endpoints
  README.md
Labels: enhancement

#213 Add a link to the Submitting to the Asset Library documentation article
  templates/submit_asset.phtml
Labels: enhancement, topic:frontend
