Repository godotengine/godot-asset-library, pull requests merged in 2023-05, with the labels that each got.

#274 Update README.md
  README.md
Labels: enhancement

#275 Changed rejection input to textarea
  templates/asset_edit.phtml
Labels: enhancement, topic:frontend

#276 Fixed missing JQuery script, changed moderator form
  templates/_footer.phtml
  templates/asset_edit.phtml
Labels: bug, enhancement, topic:frontend

#279 Improve the layout of search pages
  style/base.css
  templates/_pagination.phtml
  templates/asset_edits.phtml
  templates/assets.phtml
Labels: enhancement, topic:frontend

#280 Add basic dark mode
  assets/logo_dark.svg
  style/base.css
  templates/_footer.phtml
  templates/_header.phtml
  templates/assets.phtml
Labels: enhancement, topic:frontend

#281 Update dark theme
  style/base.css
  templates/_header.phtml
Labels: bug, enhancement, topic:frontend
