Repository godotengine/godot-asset-library, pull requests merged in 2023-06, with the labels that each got.

#282 Add a license select filter and remove the link filter
  API.md
  src/constants.php
  src/queries.php
  src/routes/asset.php
  templates/_asset_fields.phtml
  templates/asset.phtml
  templates/assets.phtml
Labels: enhancement, topic:frontend

#284 Remove bower and add jquery/bootstrap as local files
  .gitignore
  README.md
  assets/css/base.css
  assets/css/bootstrap-3.4.1.min.css
  assets/fonts/glyphicons-halflings-regular.eot
  assets/fonts/glyphicons-halflings-regular.svg
  assets/fonts/glyphicons-halflings-regular.ttf
  assets/fonts/glyphicons-halflings-regular.woff
  assets/fonts/glyphicons-halflings-regular.woff2
  assets/js/bootstrap-3.4.1.min.js
  assets/js/jquery-3.7.0.slim.min.js
  bower.json
  src/middleware.php
  templates/_footer.phtml
  templates/_header.phtml
Labels: enhancement, topic:frontend

#283 Overhaul asset-list design
  assets/css/base.css
  templates/_header.phtml
  templates/asset.phtml
  templates/asset_edits.phtml
  templates/assets.phtml
Labels: enhancement, topic:frontend

#287 Fixed approval form spacing
  templates/asset_edit.phtml
Labels: bug, topic:frontend

#288 Display feed and edit history as table
  assets/css/base.css
  src/queries.php
  templates/_header.phtml
  templates/asset_edits.phtml
  templates/feed.phtml
Labels: enhancement, topic:frontend, topic:backend
