Repository godotengine/godot-asset-library, pull requests merged in 2024-04, with the labels that each got.

#323 Added featured tag to support levels
  API.md
  src/constants.php
  src/routes/asset.php
  templates/asset.phtml
  templates/assets.phtml
Labels: enhancement, topic:frontend, topic:backend

#321 Clarify purpose of Godot version field in asset submission form
  templates/_asset_fields.phtml
Labels: enhancement, topic:frontend

#322 Rename Official support level to Featured in the frontend
  templates/assets.phtml
Labels: enhancement, topic:frontend

#325 Added Godot 4.3 to constants
  src/constants.php
Labels: enhancement, topic:backend
